name: CI
on:
  push:
    branches: [ main ]
  #pull_request:
   # branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Update site and reindex
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd /var/www/html/PPRET && sudo git pull && sudo curl http://${{ secrets.ADMINUSERNAME }}:${{ secrets.ADMINPW }}@ppret-inscriptions.huma-num.fr/admin/rdf/harvest/all.html && sudo curl http://${{ secrets.ADMINUSERNAME }}:${{ secrets.ADMINPW }}@ppret-inscriptions.huma-num.fr/admin/solr/index/all.html
