name: CI
on:
  push:
    branches: [ master ]
  #pull_request:
   # branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Update site and reindex
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd /var/www/html/PPRET && sudo git pull 
          #&& sudo curl http://ppret-inscriptions.huma-num.fr/admin/rdf/harvest/all.html && sudo curl http://ppret-inscriptions.huma-num.fr/admin/solr/index/all.html
